[tool.poetry]
name = "pprl-model"
version = "0.1.3"
description = "Data models for use with a HTTP-based service for privacy-preserving record linkage using Bloom filters."
authors = ["Maximilian Jugl <Maximilian.Jugl@medizin.uni-leipzig.de>"]
readme = "README.md"
packages = [{ include = "pprl_model" }]
license = "MIT"
repository = "https://github.com/ul-mds/pprl"
keywords = ["record linkage", "privacy", "bloom filter"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = ">=2.7.0,<3"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
ruff = "^0.4.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
