[tool.poetry]
name = "pprl-client"
version = "0.3.2"
description = "HTTP-based client for interacting with a service for privacy-preserving record linkage with Bloom filters."
authors = ["Maximilian Jugl <Maximilian.Jugl@medizin.uni-leipzig.de>"]
readme = "README.md"
packages = [{ include = "pprl_client" }]
license = "MIT"
repository = "https://github.com/ul-mds/pprl"
keywords = ["record linkage", "privacy", "bloom filter", "bitarray", "cryptography", "service", "client", "cli"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Security :: Cryptography",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.scripts]
pprl = "pprl_client.cli:run_cli"

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.27.0"
click = "^8.0.0"
pprl-model = "^0.1.5" # <3
pprl-core = "^0.1.3"
faker = { version = "^26.3.0", optional = true }
gecko-syndata = { version = "^0.3.2", optional = true }

[tool.poetry.extras]
faker = ["faker"]
gecko = ["gecko-syndata"]
all = ["faker", "gecko-syndata"]

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
ruff = "^0.5.0"
pytest-dotenv = "^0.5.2"
testcontainers = "^4.7.0"
faker = "^26.0.0"
gitpython = "^3.1.43"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
