[tool.poetry]
name = "pprl-core"
version = "0.1.3"
description = "Facilities for performing privacy-preserving record linkage with Bloom filters."
authors = ["Maximilian Jugl <Maximilian.Jugl@medizin.uni-leipzig.de>"]
readme = "README.md"
license = "MIT"
packages = [{ include = "pprl_core" }]
repository = "https://github.com/ul-mds/pprl"
keywords = ["record linkage", "privacy", "bloom filter", "bitarray", "cryptography"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = "^3.10"
bitarray = ">=2.9.0,<3"
pyphonetics = ">=0.5.0,<1"
unidecode = ">=1.3.8,<2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
ruff = "^0.4.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
