name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [pprl_core, pprl_model]
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"
      - name: Install dependencies
        working-directory: ./packages/${{ matrix.package }}
        run: poetry install
      - name: Build and publish
        working-directory: ./packages/${{ matrix.package }}
        run: poetry publish --build --no-interaction
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
